version: 2
services:
  web:
    image: <your_docker_image>
    env:
      - APP_KEY=<your_app_key>
      - APP_ENV=production
    ports:
      - 8080:8080
databases:
  default:
    image: postgres:13
    env:
      - POSTGRES_DB=<your_database_name>
      - POSTGRES_USER=<your_database_user>
      - POSTGRES_PASSWORD=<your_database_password>
